//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DotNetOpenAuth.Samples {
    
    
    public partial class OtherSamples {
        
        /// <summary>
        /// Master property.
        /// </summary>
        /// <remarks>
        /// Auto-generated property.
        /// </remarks>
        public new DotNetOpenAuth.Samples.master.SampleSite Master {
            get {
                return ((DotNetOpenAuth.Samples.master.SampleSite)(base.Master));
            }
        }
    }
}
